spring:
  application:
    name: ingester
  datasource:
    url: jdbc:postgresql://localhost:5432/ingester
    username: inboxuser
    password: inboxpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

gmail-api:
  application-name: "InboxIntelligence"
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
  redirect-uri: "http://localhost:8080/gmail-api/token-callback"
  token-url: "https://oauth2.googleapis.com/token"
  scope: "openid email https://www.googleapis.com/auth/gmail.readonly"
  pubsub-topic: "projects/inboxintelligence-01/topics/gmail-events"
  project-id: "inboxintelligence-01"
  pubsub-subscription-id: "gmail-events-sub"



